POST http://localhost:6000/Query/direct
Content-Type: application/json

{
  "params": {
  "query" : "select * from users"
  }
}

###
GET http://localhost:6000/query=
Accept: application/json

###




POST http://211.172.232.124:9201
Content-Type: application/json

{
  "key" :  "7b035420e12cc0e8ec83b7540f668cfe"
  ,"tel" : "01050348381"
,"cd" : "01090293089"
,"msg" : "테스트 메시지"
,"title" : "테스트 제목"

}